name: 'Print Env'
description: 'Print environment'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: env.sh
      shell: bash
